### ISSUE TITLE
payloads字段存在重复执行的问题

### ISSUE THREAD

**Issue by Gs52jrfnxnPXBGAW** [WAY29/pocV#12]
作者你好，我想问下我想在xray的poc下面实现shiro key检测

实现cel添加下面函数

```
			//shiro
			decls.NewFunction("shirokey",
				decls.NewOverload("shiro_key",
					[]*exprpb.Type{decls.String, decls.String},
					decls.String)),

			&functions.Overload{
				Operator: "shiro_key",
				Binary: func(key ref.Val, mode ref.Val) ref.Val {
					v1, ok := key.(types.String)
					if !ok {
						return types.ValOrErr(key, "unexpected type '%v' passed to shiro_key", key.Type())
					}
					v2, ok := mode.(types.String)
					if !ok {
						return types.ValOrErr(mode, "unexpected type '%v' passed to shiro_mode", mode.Type())
					}
					cookie := requests.GetShrioCookie(string(v1), string(v2))
					if cookie == "" {
						return types.NewErr("%v", "key b64decode failed")
					}
					return types.String(cookie)
				},
			},
```

测试poc如下所示

```
name: poc-yaml-apache-shiro-key
manual: true
transport: http
set:
  randstr: randomLowercase(8)
  shiromode1: printable("cbc")
  shiromode2: printable("gcm")
payloads:
  continue: false
  payloads:
    s1:
      key: shirokey("kPH+bIxk5D2deZiIxcaaaA==",shiromode1)
    s2:
      key: shirokey("2AvVhdsgUs0FSA3SDFAdag==",shiromode2)
rules:
  r0:
    request:
      cache: true
      method: GET
      path: /
      follow_redirects: false
      headers:
        Cookie: JSESSIONID={{randstr}};rememberMe={{key}}
    expression: |
      !response.headers["Set-Cookie"].contains("rememberMe=")
expression: r0()
detail:
  author: shadown1ng(https://github.com/shadown1ng)

```

最终发现是数据包重复执行`key: shirokey("kPH+bIxk5D2deZiIxcaaaA==",shiromode1)`，如下图所示

第一个包

<img width="732" alt="image" src="https://github.com/WAY29/pocV/assets/47938748/6b74621b-498c-401c-a125-2820c362aaba">

第二个包

<img width="745" alt="image" src="https://github.com/WAY29/pocV/assets/47938748/187ebc90-d678-4bb8-90ab-173f84cb9833">
