### ISSUE TITLE
不存在某请求头就匹配

### ISSUE THREAD

**Issue by waikeungshen** [WAY29/pocV#13]
xray中支持response.headers["X-Forwarded-For"] == ""的写法，pocV不支持，有推荐写法或者能支持一下吗

**Comment by waikeungshen** [comment]
不好意思，搞错了，是支持的，只是会报error。

**Comment by waikeungshen** [comment]
反过来也是， "X-Forwarded-For" in response.headers写法也不支持

**Comment by WAY29** [comment]
然而实际情况是这两种写法都支持,这是因为PocV使用的底层DSL即CEL是与xray一样的

一个例子如下:
```yaml
name: poc-yaml-apache-httpd-cve-2021-40438-ssrf
manual: true
transport: http
rules:
  r0:
    request:
      cache: true
      method: GET
      path: /abc
      follow_redirects: false
    expression: |
        !("location" in response.headers)
expression: r0()
detail:
  author: test

```
